### PR TITLE
Screenshot previews and automatic deploy for F-Droid

### PR DESCRIPTION
**Pull request by 6543**
This will enable screenshot previews and automatic deploy for F-Droid

(https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.liberty.android.freeotpplus.yml will need an update after this is merged - I'll send one :)  )

references:
 * https://github.com/fastlane/fastlane/blob/master/README.md
 * https://forum.f-droid.org/t/statically-validating-correctness-of-fastlane-metadata

### CODE REVIEW

**Comment by 6543** [comment]
PS: compressed screenshots with https://tinypng.com/

**Comment by 6543** [comment]
@helloworld1 do you think I should add some more screenshots? or is it OK as it is?

**Comment by helloworld1** [comment]
Thanks a lot for providing screenshots and Fastlane support for F-Droid! Screenshots are great! It OK to start with the 3 you have. So much better than nothing!

**Comment by 6543** [comment]
@helloworld1 for upcoming releases it would be good if you add a smal changelog BEFOR taging to the fastlane :)

like the other once https://github.com/helloworld1/FreeOTPPlus/tree/master/fastlane/metadata/android/en-US/changelogs

... just to mention :)

**Pull request merged**
