### PR TITLE
make progress bar green in nightmode

### PR DESCRIPTION
**Pull request by error401de**
fixes https://github.com/helloworld1/FreeOTPPlus/issues/63
Would be cool if you could check @helloworld1

### CODE REVIEW

**Comment by error401de** [comment]
Hi @helloworld1 
did you have any chance to have a look? I would appreciate to see a fixed version with both my PRs so much :)

**Comment by helloworld1** [comment]
Sorry for the delay, will take a look today

**Comment by helloworld1** [comment]
UI looks great. Thanks for making the change and sorry for the long delay to merge.

**Comment by error401de** [comment]
Thanks a lot :)
Do you have an idea when you will release the next update in the stores? Just curious.

**Comment by helloworld1** [comment]
I plan to have a release this weekend.

**Pull request merged**
