### PR TITLE
Translation Update 2021-02-11

### PR DESCRIPTION
**Pull request by 6543**

### CODE REVIEW

**Comment by 6543** [comment]
@helloworld1 just a translation update :)

**Comment by 6543** [comment]
@helloworld1 what about a new release to deliver the translations after it got merged?

**Comment by 6543** [comment]
@helloworld1 ping

**Comment by 6543** [comment]
@helloworld1 ping

**Comment by helloworld1** [comment]
Thanks a lot!

**Comment by 6543** [comment]
@helloworld1 to publish translation via F-Droid new release is needed ...

**Comment by helloworld1** [comment]
@6543 I will couple this change with the new sleep auto lock function in the next release. End of month is the expected time for the new release.

**Pull request merged**
