### PR TITLE
added Polish translation

### PR DESCRIPTION
**Pull request by mrzeznik**
Polish translation of strings.xml added.

### CODE REVIEW

**Comment by mrzeznik** [comment]
Hi! 
Here's Polish translation for the app. I hope that's possible to add it to next release.
I skipped strings with "key URI", because I don't know the context, format, etc.

**Comment by helloworld1** [comment]
The key URI is in the menu -> import / export. It means the URI for the otp keys.

**Comment by helloworld1** [comment]
I think it's ok to leave it or translate the word "key" there.

**Comment by mrzeznik** [comment]
I've checked this feature and translated this URI-part, and corrected other strings. This translation is ready now.

**Comment by helloworld1** [comment]
Thank you for the contribution! Merged.

**Pull request merged**
