### PR TITLE
Add Hungarian & Russian

### LINKED ISSUE #140: Add a new interface language to the next version
the Russian language is fully translated. please add my language for the convenience of working with the app.

### PR DESCRIPTION
**Pull request by 6543**
add 
 * hungarian
 * russian

translation

---
close  #140

### CODE REVIEW

**Comment by 6543** [comment]
@helloworld1 ping ;)

**Comment by 6543** [comment]
@helloworld1 ping ;)

**Comment by helloworld1** [comment]
Thanks a lot!

**Comment by helloworld1** [comment]
I expect to have a release end of this month. Please ping me if that does not happen.

**Pull request merged**
